# Generated by Django 5.2 on 2025-07-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_fk',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_fk',
        ),
    ]
