# Generated by Django 5.2 on 2025-07-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_order_orderitem_order_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
