# Generated by Django 5.2 on 2025-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
